// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcmbtToZDVO3Ce7ueeEJi85tYV2jVC8EQ',
    appId: '1:781860708104:web:d1de8d6fd3644e890f56bd',
    messagingSenderId: '781860708104',
    projectId: 'autohub-819f4',
    authDomain: 'autohub-819f4.firebaseapp.com',
    storageBucket: 'autohub-819f4.firebasestorage.app',
    measurementId: 'G-FNZCLVBLGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-BsVnG8o8QTywppfwlotX67Mut4ipMSw',
    appId: '1:781860708104:android:8323bdc10d8a52710f56bd',
    messagingSenderId: '781860708104',
    projectId: 'autohub-819f4',
    storageBucket: 'autohub-819f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BsVnG8o8QTywppfwlotX67Mut4ipMSw',
    appId: '1:781860708104:ios:8323bdc10d8a52710f56bd',
    messagingSenderId: '781860708104',
    projectId: 'autohub-819f4',
    storageBucket: 'autohub-819f4.firebasestorage.app',
    iosBundleId: 'com.autohub.app.autohub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BsVnG8o8QTywppfwlotX67Mut4ipMSw',
    appId: '1:781860708104:ios:8323bdc10d8a52710f56bd',
    messagingSenderId: '781860708104',
    projectId: 'autohub-819f4',
    storageBucket: 'autohub-819f4.firebasestorage.app',
    iosBundleId: 'com.autohub.app.autohub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcmbtToZDVO3Ce7ueeEJi85tYV2jVC8EQ',
    appId: '1:781860708104:web:d1de8d6fd3644e890f56bd',
    messagingSenderId: '781860708104',
    projectId: 'autohub-819f4',
    authDomain: 'autohub-819f4.firebaseapp.com',
    storageBucket: 'autohub-819f4.firebasestorage.app',
  );
}
